---
- name: DEPLOY ZENCODE
  hosts: all
  remote_user: root
  tasks:
    - name: Upload restroom configuration
      copy: src=restroom.conf dest=/home/app/restroom-template-minimal/.env
    - name: Upload zencode
      copy: src=install.zip dest=/home/app/install.zip owner=app
    - name: Publish zencode on-line
      command: unzip -o /home/app/install.zip -d /home/app/restroom-template-minimal/zencode
    - name: Find own IP
      shell: /bin/hostname -I | awk '{print $1}'
      register: ipv4
    - name: Find machine ID
      shell: cat /var/lib/dbus/machine-id
      register: macid
    - name: Patch zencode with node values
      shell: >
        sed -i -e 's/192.168.0.100/{{ ipv4.stdout }}/g' -e 's/Kenshiro/{{ ipv4.stdout }}/g' -e 's/3030/3300/g' /home/app/restroom-template-minimal/zencode/consensusroom-announce-p1.keys
    - name: Reboot server
      shell: init 6
      async: 1
      poll: 0
      ignore_errors: true
