---
- name: INSTALL RESTROOM
  hosts: zenswarm
  remote_user: app
  tasks:
    - name: Check restroom-installation
      stat:
        path: /home/app/restroom-mw
      register: restroom_installed

    - name: Install restroom from npx
      shell: npx create-restroom --all restroom-mw
      when: not restroom_installed.stat.exists

    - name: Upload restroom env configuration
      copy: src=restroom.conf dest=/home/app/restroom-mw/.env

    - name: Compile restroom with yarn
      shell: yarn
      args:
        chdir: /home/app/restroom-mw

    - name: Clean yarn's cache
      command: yarn cache clean
