---
- name: INSTALL DEVUAN
  hosts: zenswarm
  remote_user: root
  tasks:
    # - name: Install requirements
    #   apt:
    #     name: python-apt
    #     update_cache: yes
    - name: Install Devuan keyring
      shell: >-
        curl https://pkgmaster.devuan.org/devuan/pool/main/d/devuan-keyring/devuan-keyring_2017.10.03_all.deb -o devuankeys.deb && dpkg -i devuankeys.deb

    - name: Install sysvinit
      apt:
        force: yes
        name: sysvinit-core
        update_cache: yes

    - name: Disable DBus
      command: update-rc.d dbus disable

    - name: Clean up packages
      apt:
        force: yes
        autoremove: yes
        purge: yes

    - name: Reboot server
      shell: init 6
      async: 1
      poll: 0
      become: true
      ignore_errors: true
