---
- name: INSTALL DEVUAN
  hosts: zenswarm
  remote_user: root
  tasks:

    - name: Remove current apt source list
      replace:
        backup: true
        dest: /etc/apt/sources.list
        regexp: '^deb (?!http://deb.devuan.org).*'

    - name: Add Devuan apt source
      lineinfile:
        dest: /etc/apt/sources.list
        line: 'deb http://deb.devuan.org/merged chimaera main'
        state: present

    - name: Migrate to Devuan (dist-upgrade, takes time...)
      apt:
        upgrade: dist
        update_cache: yes

    - name: Remove and purge systemd
      apt:
        state: absent
        name: dbus-user-session libnss-systemd systemd plymouth
        purge: yes
        autoremove: yes

    - name: Reboot server
      shell: init 6
      async: 1
      poll: 0
      become: true
      ignore_errors: true
