---
- name: CONFIGURE APP LOGIN
  hosts: all
  become: yes
  tasks:
    - name: Setup default password
      user:
        name: root
        update_password: always
        password: $6$BKITGIpl6qrOqHK4$oiUXEGpNoSF9ZQBnNiAIiuEKdzq1sWTLg37t1JBFEvCUepcr9lU2guEEtoqT1V8fbU0uVckC1TzqEOxsPxP8W1
        # zenswarm

    - name: Create a login user
      user:
        name: "app"
        state: present
        shell: /bin/bash
        uid: 1000
        home: /home/app
        update_password: always
        password: $6$BKITGIpl6qrOqHK4$oiUXEGpNoSF9ZQBnNiAIiuEKdzq1sWTLg37t1JBFEvCUepcr9lU2guEEtoqT1V8fbU0uVckC1TzqEOxsPxP8W1

    # - name: copy ssh keys from root to app
    #   shell:
    #     cp -ra ~/.ssh /home/app/ \
    #     && chown -R app:app /home/app/.ssh
